wandb_version: 1

space_description:
  desc: null
  value: EnvSpaceDescription(action_space=Box(-1.0, 1.0, (8,), float32), observation_space=Box(-inf,
    inf, (27,), float64))
gamma:
  desc: null
  value: 0.99
name:
  desc: null
  value: Cascade
training_alg_cfg:
  desc: null
  value: 'PPOConfig(space_description=EnvSpaceDescription(action_space=Box(-1.0, 1.0,
    (8,), float32), observation_space=Box(-inf, inf, (27,), float64)), gamma=0.99,
    name=''PPO_Vanilla'', learning_rate=0.0003, num_envs=1, num_steps=2048, gae_lambda=0.95,
    num_minibatches=32, update_epochs=10, clip_coef=0.2, action_ent_coef=0, vf_coef=0.5,
    max_grad_norm=0.5, norm_adv=True, clip_vloss=True, anneal_lr=True, cuda=False,
    net_conf=NetworkConfig(class_name=''ActorCritic'', args_dict={''shared'': None,
    ''actor'': NetworkConfig(class_name=''ActorHead'', args_dict={''mean'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': 27, ''output_size'': 8, ''hidden_sizes'': (64, 64),
    ''activation_last_layer'': False, ''init_std'': [1.4142135623730951, 1.4142135623730951,
    0.01], ''init_bias_const'': [0.0, 0.0, 0.0]}), ''logstd'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': None, ''output_size'': 8, ''hidden_sizes'': None})}),
    ''critic'': NetworkConfig(class_name=''FFNet'', args_dict={''input_size'': 27,
    ''output_size'': 1, ''hidden_sizes'': (64, 64), ''activation_last_layer'': False,
    ''init_std'': (1.4142135623730951, 1.4142135623730951, 1.0), ''init_bias_const'':
    (0.0, 0.0, 0.0)})}), attention_vent_coef=0, attention_hent_coef=0, chooser_epochs=0,
    action_epochs=0, fallback_coef=0.0)'
init_net_cfg:
  desc: null
  value: 'NetworkConfig(class_name=''ActorCritic'', args_dict={''shared'': None, ''actor'':
    NetworkConfig(class_name=''ActorHead'', args_dict={''mean'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': 27, ''output_size'': 8, ''hidden_sizes'': (16, 16),
    ''preset_params'': [], ''activation_last_layer'': False, ''init_std'': (1.4142135623730951,
    1.4142135623730951, 0.01), ''init_bias_const'': (0.0, 0.0, 0.0)}), ''logstd'':
    NetworkConfig(class_name=''FFNet'', args_dict={''input_size'': None, ''output_size'':
    8, ''hidden_sizes'': None})}), ''critic'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': 27, ''output_size'': 1, ''hidden_sizes'': (64, 64),
    ''activation_last_layer'': False, ''init_std'': (1.4142135623730951, 1.4142135623730951,
    1.0), ''init_bias_const'': (0.0, 0.0, 0.0)})})'
stacked_net_cfg:
  desc: null
  value: 'NetworkConfig(class_name=''ActorCritic'', args_dict={''shared'': None, ''actor'':
    NetworkConfig(class_name=''ActorHead'', args_dict={''mean'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': 27, ''output_size'': 9, ''hidden_sizes'': (16, 16),
    ''preset_params'': [(4, True, 8, 0.0)], ''activation_last_layer'': False, ''init_std'':
    (1.4142135623730951, 1.4142135623730951, 0.01), ''init_bias_const'': (0.0, 0.0,
    0.0)}), ''logstd'': NetworkConfig(class_name=''FFNet'', args_dict={''input_size'':
    None, ''output_size'': 8, ''hidden_sizes'': None})}), ''critic'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': 27, ''output_size'': 1, ''hidden_sizes'': (64, 64),
    ''activation_last_layer'': False, ''init_std'': (1.4142135623730951, 1.4142135623730951,
    1.0), ''init_bias_const'': (0.0, 0.0, 0.0)})})'
base_steps:
  desc: null
  value: 1000000
propagate_action:
  desc: null
  value: false
propagate_value:
  desc: null
  value: false
train_only_top_net:
  desc: null
  value: false
sequential:
  desc: null
  value: true
stacks:
  desc: null
  value: -1
cyclical_lr:
  desc: null
  value: true
use_fallback_weight:
  desc: null
  value: false
env_description:
  desc: null
  value: Ant-v4;agent_config:Cascade
identifier:
  desc: null
  value: qeALN
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693414253.090397
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.14.2
      8:
      - 3
      - 5
