wandb_version: 1

space_description:
  desc: null
  value: EnvSpaceDescription(action_space=Box(-1.0, 1.0, (8,), float32), observation_space=Box(-inf,
    inf, (27,), float64))
gamma:
  desc: null
  value: 0.99
name:
  desc: null
  value: PPO_Vanilla
learning_rate:
  desc: null
  value: 0.0003
num_envs:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 2048
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 32
update_epochs:
  desc: null
  value: 10
clip_coef:
  desc: null
  value: 0.2
action_ent_coef:
  desc: null
  value: 0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
norm_adv:
  desc: null
  value: true
clip_vloss:
  desc: null
  value: true
anneal_lr:
  desc: null
  value: false
cuda:
  desc: null
  value: false
net_conf:
  desc: null
  value: 'NetworkConfig(class_name=''ActorCritic'', args_dict={''shared'': None, ''actor'':
    NetworkConfig(class_name=''ActorHead'', args_dict={''mean'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': 27, ''output_size'': 8, ''hidden_sizes'': (64, 64),
    ''activation_last_layer'': False, ''init_std'': [1.4142135623730951, 1.4142135623730951,
    0.01], ''init_bias_const'': [0.0, 0.0, 0.0]}), ''logstd'': NetworkConfig(class_name=''FFNet'',
    args_dict={''input_size'': None, ''output_size'': 8, ''hidden_sizes'': None})}),
    ''critic'': NetworkConfig(class_name=''FFNet'', args_dict={''input_size'': 27,
    ''output_size'': 1, ''hidden_sizes'': (64, 64), ''activation_last_layer'': False,
    ''init_std'': (1.4142135623730951, 1.4142135623730951, 1.0), ''init_bias_const'':
    (0.0, 0.0, 0.0)})})'
attention_vent_coef:
  desc: null
  value: 0
attention_hent_coef:
  desc: null
  value: 0
chooser_epochs:
  desc: null
  value: 0
action_epochs:
  desc: null
  value: 0
fallback_coef:
  desc: null
  value: 0
phases:
  desc: null
  value: 3
phase_duration:
  desc: null
  value: 666667
phase_mode:
  desc: null
  value: average
env_description:
  desc: null
  value: Ant-v4;agent_config:VanillaPPO
identifier:
  desc: null
  value: WCHyj
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693910878.212299
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.14.2
      8:
      - 3
      - 5
